[package]
name = "cheatbook"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.7" }
#bevy = { git = "https://github.com/bevyengine/bevy" }

[dev-dependencies]
image = "0.23"
winit = "0.26"
