[package]
name = "cheatbook"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.9" }
# bevy = { git = "https://github.com/bevyengine/bevy" }

[dev-dependencies]
image = "0.24.5"
winit = "0.27"
