[package]
name = "cheatbook013"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13" }
# bevy = { git = "https://github.com/bevyengine/bevy" }

[dev-dependencies]
image = "0.24"
winit = "0.29"

# [[bin]]
# name = "input-char"
# path = "src/input/char.rs"
